CREATE USER MYUSER
IDENTIFIED BY oracle4U
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;

GRANT 
CREATE SESSION,
ALTER SESSION,
CREATE TABLE,
CREATE SEQUENCE,
CREATE VIEW,
CREATE PROCEDURE,
CREATE TRIGGER
TO MYUSER;